title: Cuongtobi blog
email: cuongvuong299@gmail.com
description: >-
  Cuongtobi blog, IT blog, dev blog, learn ruby, learn ruby on rails, learn javascript,
  learn mysql
baseurl: ""
url: ""
github_username: cuongtobi
paginate: 20
paginate_path: "/page/:num"
permalink: "/:categories/:title"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
