title: cuongtobi - blog công nghệ
email: cuongvuong299@gmail.com
description: >-
  cuongtobi - blog công nghệ, chia sẻ kiến thức lập trình, blockchain, cryptocurrency.
baseurl: ""
url: "https://cuongtobi.github.io"
github_username: cuongtobi
paginate: 10
paginate_path: "/page/:num"
permalink: "/:categories/:title"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
